language: scala
jdk: oraclejdk8
compiler:
  - gcc
before_script:
  - 'bash ./install-opencv.sh'
script:
  - 'sbt test'
  - 'if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then bash ./style-checks.sh; fi'
notifications:
  slack:
    rooms:
      - team846:C7msa8tAKGdHScWVPPVL3DnB
    on_success: change
    on_failure: always
