language: scala
jdk: oraclejdk8
after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST == "true" ]]; then bash ./style-checks.sh; fi'
notifications:
  slack:
    rooms:
      - team846:C7msa8tAKGdHScWVPPVL3DnB
    on_success: change
    on_failure: always
